name: Skyblock
version: '${project.version}'
main: skyblock.skyblock.Skyblock
api-version: 1.19
authors: [ MaettisDE ]
description: Hypixel Skyblock nachprogrammieren
website: matev3.de


commands:
  minion:
    description: Gives you a minion, only for Development purposes
  setLobby:
    description: Set the Location of the Lobby!
  link:
    description: Link your Minecraft Account to your Discord Account
    usage: /link
    permission: skyblock.link